plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:metric-comment"))
    implementation(project(":repository:photo-comment"))
    implementation(project(":repository:login-location"))
    implementation(project(":repository:note-comment"))
    implementation(project(":repository:identity-post"))
    implementation(project(":repository:session-post"))
    implementation(project(":repository:event-comment"))
    implementation(project(":repository:status-search"))
    implementation(project(":repository:push-location"))
    implementation(project(":repository:timer-post"))
    implementation(project(":repository:log-comment"))
    implementation(project(":repository:post-post"))
    implementation(project(":repository:search-comment"))
    implementation(project(":repository:podcast-comment"))
    implementation(project(":repository:user-post"))
    implementation(project(":repository:comment-comment"))
    implementation(project(":repository:analytics-post"))
    implementation(project(":repository:todo-search"))
    implementation(project(":repository:audio-search"))
    implementation(project(":repository:comment-location"))
    implementation(project(":repository:account-search"))
    implementation(project(":repository:media-comment"))
    implementation(project(":repository:account-post"))
    implementation(project(":repository:calendar-search"))
    implementation(project(":repository:alarm-comment"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}