plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:share-cart"))
    implementation(project(":repository:network-cart"))
    implementation(project(":repository:session-checkout"))
    implementation(project(":repository:account-checkout"))
    implementation(project(":repository:event-cart"))
    implementation(project(":repository:push-cart"))
    implementation(project(":repository:gallery-checkout"))
    implementation(project(":repository:metric-checkout"))
    implementation(project(":repository:contact-cart"))
    implementation(project(":repository:group-checkout"))
    implementation(project(":repository:message-cart"))
    implementation(project(":repository:task-checkout"))
    implementation(project(":repository:podcast-checkout"))
    implementation(project(":repository:sync-cart"))
    implementation(project(":repository:location-cart"))
    implementation(project(":repository:log-cart"))
    implementation(project(":repository:notification-cart"))
    implementation(project(":repository:setting-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}