plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:list-comment"))
    implementation(project(":repository:push-post"))
    implementation(project(":repository:session-post"))
    implementation(project(":repository:document-post"))
    implementation(project(":repository:news-comment"))
    implementation(project(":repository:share-comment"))
    implementation(project(":repository:report-search"))
    implementation(project(":repository:status-comment"))
    implementation(project(":repository:checkout-location"))
    implementation(project(":repository:playlist-post"))
    implementation(project(":repository:map-comment"))
    implementation(project(":repository:feed-search"))
    implementation(project(":repository:search-comment"))
    implementation(project(":repository:share-post"))
    implementation(project(":repository:session-comment"))
    implementation(project(":repository:news-search"))
    implementation(project(":repository:push-search"))
    implementation(project(":repository:network-post"))
    implementation(project(":repository:post-search"))
    implementation(project(":repository:identity-location"))
    implementation(project(":repository:account-search"))
    implementation(project(":repository:task-search"))
    implementation(project(":repository:log-search"))
    implementation(project(":repository:contact-post"))
    implementation(project(":repository:event-post"))
    implementation(project(":repository:sync-post"))
    implementation(project(":repository:account-comment"))
    implementation(project(":repository:status-post"))
    implementation(project(":repository:location-comment"))
    implementation(project(":repository:forecast-comment"))
    implementation(project(":repository:photo-post"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}