plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:analytics-cart"))
    implementation(project(":domain:network-cart"))
    implementation(project(":domain:timer-checkout"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:sync-user"))
    implementation(project(":domain:alarm-cart"))
    implementation(project(":domain:user-user"))
    implementation(project(":domain:push-cart"))
    implementation(project(":domain:status-checkout"))
    implementation(project(":domain:task-user"))
    implementation(project(":domain:metric-checkout"))
    implementation(project(":domain:login-cart"))
    implementation(project(":domain:document-user"))
    implementation(project(":domain:map-checkout"))
    implementation(project(":domain:file-cart"))
    implementation(project(":domain:cart-cart"))
    implementation(project(":domain:list-checkout"))
    implementation(project(":domain:network-user"))
    implementation(project(":domain:location-cart"))
    implementation(project(":domain:log-cart"))
    implementation(project(":domain:log-user"))
    implementation(project(":domain:login-user"))
    implementation(project(":domain:post-cart"))
    implementation(project(":domain:session-cart"))
    implementation(project(":domain:file-user"))
    implementation(project(":domain:playlist-cart"))
    implementation(project(":domain:event-checkout"))
    implementation(project(":domain:podcast-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}