plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:news-feed"))
    implementation(project(":domain:profile-profile"))
    implementation(project(":domain:analytics-user"))
    implementation(project(":domain:setting-user"))
    implementation(project(":domain:group-user"))
    implementation(project(":domain:comment-profile"))
    implementation(project(":domain:user-profile"))
    implementation(project(":domain:cart-comment"))
    implementation(project(":domain:sync-profile"))
    implementation(project(":domain:audio-user"))
    implementation(project(":domain:checkout-feed"))
    implementation(project(":domain:list-feed"))
    implementation(project(":domain:message-feed"))
    implementation(project(":domain:news-user"))
    implementation(project(":domain:profile-feed"))
    implementation(project(":domain:file-feed"))
    implementation(project(":domain:gallery-user"))
    implementation(project(":domain:status-user"))
    implementation(project(":domain:message-profile"))
    implementation(project(":domain:log-feed"))
    implementation(project(":domain:search-profile"))
    implementation(project(":domain:article-profile"))
    implementation(project(":domain:alarm-profile"))
    implementation(project(":domain:push-profile"))
    implementation(project(":domain:podcast-feed"))
    implementation(project(":domain:push-feed"))
    implementation(project(":domain:notification-feed"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}