plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:account-identity"))
    implementation(project(":feature:contact-user"))
    implementation(project(":feature:article-checkout"))
    implementation(project(":feature:user-cart"))
    implementation(project(":feature:message-cart"))
    implementation(project(":feature:metric-identity"))
    implementation(project(":feature:login-checkout"))
    implementation(project(":feature:photo-identity"))
    implementation(project(":feature:audio-checkout"))
    implementation(project(":feature:profile-checkout"))
    implementation(project(":feature:todo-identity"))
    implementation(project(":feature:cart-cart"))
    implementation(project(":feature:playlist-checkout"))
    implementation(project(":feature:weather-checkout"))
    implementation(project(":feature:group-checkout"))
    implementation(project(":feature:feed-identity"))
    implementation(project(":feature:playlist-identity"))
    implementation(project(":feature:checkout-identity"))
    implementation(project(":feature:event-checkout"))
    implementation(project(":feature:status-cart"))
    implementation(project(":feature:contact-checkout"))
    implementation(project(":feature:login-user"))
    implementation(project(":feature:checkout-checkout"))
    implementation(project(":feature:share-cart"))
    implementation(project(":feature:video-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}