plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:account-post"))
    implementation(project(":repository:network-post"))
    implementation(project(":repository:search-search"))
    implementation(project(":repository:sync-search"))
    implementation(project(":repository:analytics-post"))
    implementation(project(":repository:news-comment"))
    implementation(project(":repository:group-search"))
    implementation(project(":repository:news-post"))
    implementation(project(":repository:sync-post"))
    implementation(project(":repository:list-search"))
    implementation(project(":repository:comment-search"))
    implementation(project(":repository:push-location"))
    implementation(project(":repository:map-search"))
    implementation(project(":repository:audio-post"))
    implementation(project(":repository:feed-search"))
    implementation(project(":repository:photo-post"))
    implementation(project(":repository:user-location"))
    implementation(project(":repository:setting-search"))
    implementation(project(":repository:post-post"))
    implementation(project(":repository:alarm-comment"))
    implementation(project(":repository:report-search"))
    implementation(project(":repository:media-search"))
    implementation(project(":repository:file-post"))
    implementation(project(":repository:location-comment"))
    implementation(project(":repository:message-search"))
    implementation(project(":repository:calendar-search"))
    implementation(project(":repository:session-comment"))
    implementation(project(":repository:profile-location"))
    implementation(project(":repository:metric-search"))
    implementation(project(":repository:article-post"))
    implementation(project(":repository:podcast-search"))
    implementation(project(":repository:analytics-search"))
    implementation(project(":repository:log-search"))
    implementation(project(":repository:cart-search"))
    implementation(project(":repository:weather-search"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}