plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:report-profile"))
    implementation(project(":domain:message-feed"))
    implementation(project(":domain:user-feed"))
    implementation(project(":domain:photo-profile"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:playlist-feed"))
    implementation(project(":domain:feed-user"))
    implementation(project(":domain:map-feed"))
    implementation(project(":domain:weather-user"))
    implementation(project(":domain:forecast-feed"))
    implementation(project(":domain:checkout-comment"))
    implementation(project(":domain:status-user"))
    implementation(project(":domain:push-feed"))
    implementation(project(":domain:task-feed"))
    implementation(project(":domain:contact-profile"))
    implementation(project(":domain:feed-comment"))
    implementation(project(":domain:session-feed"))
    implementation(project(":domain:session-profile"))
    implementation(project(":domain:task-profile"))
    implementation(project(":domain:map-user"))
    implementation(project(":domain:audio-profile"))
    implementation(project(":domain:alarm-user"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}