plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:push-checkout"))
    implementation(project(":feature:event-login"))
    implementation(project(":feature:report-identity"))
    implementation(project(":feature:file-identity"))
    implementation(project(":feature:contact-identity"))
    implementation(project(":feature:comment-identity"))
    implementation(project(":feature:session-checkout"))
    implementation(project(":feature:notification-checkout"))
    implementation(project(":feature:network-checkout"))
    implementation(project(":feature:log-login"))
    implementation(project(":feature:video-identity"))
    implementation(project(":feature:calendar-identity"))
    implementation(project(":feature:playlist-identity"))
    implementation(project(":feature:sync-login"))
    implementation(project(":feature:weather-login"))
    implementation(project(":feature:post-checkout"))
    implementation(project(":feature:profile-checkout"))
    implementation(project(":feature:analytics-login"))
    implementation(project(":feature:push-identity"))
    implementation(project(":feature:article-login"))
    implementation(project(":feature:setting-login"))
    implementation(project(":feature:podcast-identity"))
    implementation(project(":feature:identity-identity"))
    implementation(project(":feature:report-checkout"))
    implementation(project(":feature:gallery-login"))
    implementation(project(":feature:task-identity"))
    implementation(project(":feature:metric-identity"))
    implementation(project(":feature:alarm-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}