plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:post-feed"))
    implementation(project(":repository:metric-feed"))
    implementation(project(":repository:comment-profile"))
    implementation(project(":repository:location-profile"))
    implementation(project(":repository:audio-feed"))
    implementation(project(":repository:cart-profile"))
    implementation(project(":repository:article-feed"))
    implementation(project(":repository:push-feed"))
    implementation(project(":repository:forecast-user"))
    implementation(project(":repository:setting-profile"))
    implementation(project(":repository:contact-profile"))
    implementation(project(":repository:sync-feed"))
    implementation(project(":repository:push-profile"))
    implementation(project(":repository:cart-feed"))
    implementation(project(":repository:note-profile"))
    implementation(project(":repository:video-profile"))
    implementation(project(":repository:alarm-feed"))
    implementation(project(":repository:group-feed"))
    implementation(project(":repository:media-profile"))
    implementation(project(":repository:news-user"))
    implementation(project(":repository:media-user"))
    implementation(project(":repository:message-profile"))
    implementation(project(":repository:news-feed"))
    implementation(project(":repository:report-profile"))
    implementation(project(":repository:list-user"))
    implementation(project(":repository:status-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}