plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:network-user"))
    implementation(project(":domain:analytics-cart"))
    implementation(project(":domain:audio-cart"))
    implementation(project(":domain:comment-cart"))
    implementation(project(":domain:setting-cart"))
    implementation(project(":domain:task-cart"))
    implementation(project(":domain:login-user"))
    implementation(project(":domain:photo-checkout"))
    implementation(project(":domain:news-checkout"))
    implementation(project(":domain:gallery-cart"))
    implementation(project(":domain:report-user"))
    implementation(project(":domain:todo-cart"))
    implementation(project(":domain:contact-user"))
    implementation(project(":domain:document-user"))
    implementation(project(":domain:video-checkout"))
    implementation(project(":domain:article-cart"))
    implementation(project(":domain:timer-user"))
    implementation(project(":domain:feed-cart"))
    implementation(project(":domain:identity-user"))
    implementation(project(":domain:metric-checkout"))
    implementation(project(":domain:todo-user"))
    implementation(project(":domain:timer-checkout"))
    implementation(project(":domain:group-user"))
    implementation(project(":domain:contact-cart"))
    implementation(project(":domain:location-user"))
    implementation(project(":domain:share-cart"))
    implementation(project(":domain:event-user"))
    implementation(project(":domain:push-user"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}