plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:log-checkout"))
    implementation(project(":feature:list-cart"))
    implementation(project(":feature:message-checkout"))
    implementation(project(":feature:list-identity"))
    implementation(project(":feature:checkout-checkout"))
    implementation(project(":feature:identity-cart"))
    implementation(project(":feature:task-identity"))
    implementation(project(":feature:forecast-cart"))
    implementation(project(":feature:location-checkout"))
    implementation(project(":feature:profile-cart"))
    implementation(project(":feature:podcast-cart"))
    implementation(project(":feature:contact-user"))
    implementation(project(":feature:analytics-identity"))
    implementation(project(":feature:report-cart"))
    implementation(project(":feature:metric-cart"))
    implementation(project(":feature:event-cart"))
    implementation(project(":feature:cart-user"))
    implementation(project(":feature:podcast-identity"))
    implementation(project(":feature:video-identity"))
    implementation(project(":feature:photo-checkout"))
    implementation(project(":feature:group-checkout"))
    implementation(project(":feature:contact-cart"))
    implementation(project(":feature:audio-checkout"))
    implementation(project(":feature:search-checkout"))
    implementation(project(":feature:network-identity"))
    implementation(project(":feature:todo-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}