plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:podcast-contact"))
    implementation(project(":core:comment-contact"))
    implementation(project(":core:user"))
    implementation(project(":core:photo-contact"))
    implementation(project(":core:article-login"))
    implementation(project(":core:post-contact"))
    implementation(project(":core:playlist-login"))
    implementation(project(":core:post-login"))
    implementation(project(":core:checkout-login"))
    implementation(project(":core:photo"))
    implementation(project(":core:share-login"))
    implementation(project(":core:file-login"))
    implementation(project(":core:log-contact"))
    implementation(project(":core:contact-login"))
    implementation(project(":core:alarm-login"))
    implementation(project(":core:setting-login"))
    implementation(project(":core:event"))
    implementation(project(":core:network-login"))
    implementation(project(":core:document-login"))
    implementation(project(":core:playlist-contact"))
    implementation(project(":core:video"))
    implementation(project(":core:article-contact"))
    implementation(project(":core:event-contact"))
    implementation(project(":core:profile-contact"))
    implementation(project(":core:user-login"))
    implementation(project(":core:session-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}