plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:alarm-user"))
    implementation(project(":domain:metric-checkout"))
    implementation(project(":domain:location-cart"))
    implementation(project(":domain:comment-cart"))
    implementation(project(":domain:log-checkout"))
    implementation(project(":domain:note-user"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:checkout-cart"))
    implementation(project(":domain:calendar-cart"))
    implementation(project(":domain:group-cart"))
    implementation(project(":domain:article-checkout"))
    implementation(project(":domain:video-cart"))
    implementation(project(":domain:task-cart"))
    implementation(project(":domain:video-checkout"))
    implementation(project(":domain:note-cart"))
    implementation(project(":domain:share-user"))
    implementation(project(":domain:media-cart"))
    implementation(project(":domain:task-checkout"))
    implementation(project(":domain:gallery-checkout"))
    implementation(project(":domain:document-checkout"))
    implementation(project(":domain:search-user"))
    implementation(project(":domain:post-cart"))
    implementation(project(":domain:push-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}