plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:forecast-post"))
    implementation(project(":repository:media-post"))
    implementation(project(":repository:identity-search"))
    implementation(project(":repository:account-comment"))
    implementation(project(":repository:post-location"))
    implementation(project(":repository:message-search"))
    implementation(project(":repository:analytics-search"))
    implementation(project(":repository:timer-post"))
    implementation(project(":repository:group-search"))
    implementation(project(":repository:search-location"))
    implementation(project(":repository:forecast-comment"))
    implementation(project(":repository:alarm-search"))
    implementation(project(":repository:setting-comment"))
    implementation(project(":repository:network-search"))
    implementation(project(":repository:post-post"))
    implementation(project(":repository:event-comment"))
    implementation(project(":repository:group-comment"))
    implementation(project(":repository:user-post"))
    implementation(project(":repository:weather-post"))
    implementation(project(":repository:status-search"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}