plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:share-comment"))
    implementation(project(":repository:user-search"))
    implementation(project(":repository:news-comment"))
    implementation(project(":repository:alarm-search"))
    implementation(project(":repository:setting-search"))
    implementation(project(":repository:profile-post"))
    implementation(project(":repository:gallery-comment"))
    implementation(project(":repository:account-post"))
    implementation(project(":repository:session-comment"))
    implementation(project(":repository:checkout-post"))
    implementation(project(":repository:session-search"))
    implementation(project(":repository:calendar-post"))
    implementation(project(":repository:sync-search"))
    implementation(project(":repository:comment-post"))
    implementation(project(":repository:report-search"))
    implementation(project(":repository:notification-search"))
    implementation(project(":repository:group-comment"))
    implementation(project(":repository:push-search"))
    implementation(project(":repository:photo-search"))
    implementation(project(":repository:account-search"))
    implementation(project(":repository:notification-comment"))
    implementation(project(":repository:audio-post"))
    implementation(project(":repository:gallery-search"))
    implementation(project(":repository:report-post"))
    implementation(project(":repository:setting-comment"))
    implementation(project(":repository:list-comment"))
    implementation(project(":repository:user-post"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}