plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:cart-contact"))
    implementation(project(":core:login-contact"))
    implementation(project(":core:gallery-contact"))
    implementation(project(":core:login-login"))
    implementation(project(":core:note-contact"))
    implementation(project(":core:feed-login"))
    implementation(project(":core:profile-contact"))
    implementation(project(":core:gallery"))
    implementation(project(":core:share-contact"))
    implementation(project(":core:status"))
    implementation(project(":core:report-contact"))
    implementation(project(":core:cart"))
    implementation(project(":core:message"))
    implementation(project(":core:map"))
    implementation(project(":core:forecast-contact"))
    implementation(project(":core:weather-contact"))
    implementation(project(":core:comment"))
    implementation(project(":core:identity-contact"))
    implementation(project(":core:contact-contact"))
    implementation(project(":core:list"))
    implementation(project(":core:notification"))
    implementation(project(":core:share"))
    implementation(project(":core:session"))
    implementation(project(":core:setting"))
    implementation(project(":core:todo-contact"))
    implementation(project(":core:analytics-contact"))
    implementation(project(":core:checkout-login"))
    implementation(project(":core:user-login"))
    implementation(project(":core:profile-login"))
    implementation(project(":core:alarm"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}