plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:map-cart"))
    implementation(project(":domain:file-user"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:podcast-checkout"))
    implementation(project(":domain:share-user"))
    implementation(project(":domain:task-cart"))
    implementation(project(":domain:photo-cart"))
    implementation(project(":domain:cart-user"))
    implementation(project(":domain:note-checkout"))
    implementation(project(":domain:feed-user"))
    implementation(project(":domain:post-user"))
    implementation(project(":domain:report-user"))
    implementation(project(":domain:calendar-checkout"))
    implementation(project(":domain:article-cart"))
    implementation(project(":domain:task-user"))
    implementation(project(":domain:location-user"))
    implementation(project(":domain:status-cart"))
    implementation(project(":domain:setting-cart"))
    implementation(project(":domain:note-cart"))
    implementation(project(":domain:status-checkout"))
    implementation(project(":domain:account-cart"))
    implementation(project(":domain:event-cart"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:user-cart"))
    implementation(project(":domain:media-cart"))
    implementation(project(":domain:playlist-cart"))
    implementation(project(":domain:weather-checkout"))
    implementation(project(":domain:location-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}