plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:event-feed"))
    implementation(project(":repository:news-profile"))
    implementation(project(":repository:forecast-user"))
    implementation(project(":repository:event-profile"))
    implementation(project(":repository:log-feed"))
    implementation(project(":repository:alarm-profile"))
    implementation(project(":repository:photo-profile"))
    implementation(project(":repository:sync-profile"))
    implementation(project(":repository:group-profile"))
    implementation(project(":repository:session-profile"))
    implementation(project(":repository:user-profile"))
    implementation(project(":repository:profile-feed"))
    implementation(project(":repository:post-profile"))
    implementation(project(":repository:location-feed"))
    implementation(project(":repository:location-profile"))
    implementation(project(":repository:sync-feed"))
    implementation(project(":repository:status-feed"))
    implementation(project(":repository:account-feed"))
    implementation(project(":repository:metric-profile"))
    implementation(project(":repository:news-user"))
    implementation(project(":repository:notification-profile"))
    implementation(project(":repository:document-profile"))
    implementation(project(":repository:article-feed"))
    implementation(project(":repository:setting-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}