plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:message-login"))
    implementation(project(":feature:user-identity"))
    implementation(project(":feature:audio-identity"))
    implementation(project(":feature:session-login"))
    implementation(project(":feature:location-checkout"))
    implementation(project(":feature:report-login"))
    implementation(project(":feature:feed-identity"))
    implementation(project(":feature:event-login"))
    implementation(project(":feature:calendar-identity"))
    implementation(project(":feature:status-login"))
    implementation(project(":feature:network-checkout"))
    implementation(project(":feature:profile-checkout"))
    implementation(project(":feature:search-checkout"))
    implementation(project(":feature:analytics-identity"))
    implementation(project(":feature:account-checkout"))
    implementation(project(":feature:cart-checkout"))
    implementation(project(":feature:post-checkout"))
    implementation(project(":feature:login-identity"))
    implementation(project(":feature:log-login"))
    implementation(project(":feature:location-identity"))
    implementation(project(":feature:forecast-identity"))
    implementation(project(":feature:article-identity"))
    implementation(project(":feature:todo-identity"))
    implementation(project(":feature:gallery-identity"))
    implementation(project(":feature:podcast-identity"))
    implementation(project(":feature:identity-identity"))
    implementation(project(":feature:message-identity"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:group-checkout"))
    implementation(project(":feature:gallery-login"))
    implementation(project(":feature:group-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}