plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:alarm-user"))
    implementation(project(":domain:group-user"))
    implementation(project(":domain:contact-cart"))
    implementation(project(":domain:note-checkout"))
    implementation(project(":domain:report-cart"))
    implementation(project(":domain:push-cart"))
    implementation(project(":domain:article-checkout"))
    implementation(project(":domain:cart-cart"))
    implementation(project(":domain:event-cart"))
    implementation(project(":domain:network-cart"))
    implementation(project(":domain:video-cart"))
    implementation(project(":domain:media-checkout"))
    implementation(project(":domain:notification-cart"))
    implementation(project(":domain:comment-user"))
    implementation(project(":domain:todo-user"))
    implementation(project(":domain:calendar-checkout"))
    implementation(project(":domain:session-cart"))
    implementation(project(":domain:notification-user"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:metric-checkout"))
    implementation(project(":domain:identity-user"))
    implementation(project(":domain:task-user"))
    implementation(project(":domain:share-user"))
    implementation(project(":domain:metric-cart"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:document-cart"))
    implementation(project(":domain:checkout-user"))
    implementation(project(":domain:timer-checkout"))
    implementation(project(":domain:profile-cart"))
    implementation(project(":domain:login-cart"))
    implementation(project(":domain:status-user"))
    implementation(project(":domain:setting-cart"))
    implementation(project(":domain:log-user"))
    implementation(project(":domain:analytics-user"))
    implementation(project(":domain:group-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}