plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:note-checkout"))
    implementation(project(":feature:news-identity"))
    implementation(project(":feature:login-user"))
    implementation(project(":feature:checkout-identity"))
    implementation(project(":feature:calendar-cart"))
    implementation(project(":feature:event-identity"))
    implementation(project(":feature:list-cart"))
    implementation(project(":feature:video-checkout"))
    implementation(project(":feature:gallery-checkout"))
    implementation(project(":feature:note-identity"))
    implementation(project(":feature:setting-checkout"))
    implementation(project(":feature:metric-cart"))
    implementation(project(":feature:file-cart"))
    implementation(project(":feature:setting-cart"))
    implementation(project(":feature:event-cart"))
    implementation(project(":feature:session-checkout"))
    implementation(project(":feature:forecast-checkout"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:todo-identity"))
    implementation(project(":feature:login-cart"))
    implementation(project(":feature:network-checkout"))
    implementation(project(":feature:checkout-cart"))
    implementation(project(":feature:report-cart"))
    implementation(project(":feature:checkout-checkout"))
    implementation(project(":feature:notification-identity"))
    implementation(project(":feature:map-identity"))
    implementation(project(":feature:sync-cart"))
    implementation(project(":feature:account-cart"))
    implementation(project(":feature:cart-checkout"))
    implementation(project(":feature:group-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}