plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:podcast-profile"))
    implementation(project(":repository:contact-feed"))
    implementation(project(":repository:log-feed"))
    implementation(project(":repository:weather-user"))
    implementation(project(":repository:playlist-profile"))
    implementation(project(":repository:network-feed"))
    implementation(project(":repository:file-feed"))
    implementation(project(":repository:report-feed"))
    implementation(project(":repository:weather-profile"))
    implementation(project(":repository:podcast-feed"))
    implementation(project(":repository:metric-feed"))
    implementation(project(":repository:map-feed"))
    implementation(project(":repository:search-profile"))
    implementation(project(":repository:article-user"))
    implementation(project(":repository:file-profile"))
    implementation(project(":repository:cart-profile"))
    implementation(project(":repository:event-feed"))
    implementation(project(":repository:group-feed"))
    implementation(project(":repository:list-user"))
    implementation(project(":repository:network-profile"))
    implementation(project(":repository:login-profile"))
    implementation(project(":repository:location-profile"))
    implementation(project(":repository:video-user"))
    implementation(project(":repository:user-profile"))
    implementation(project(":repository:notification-feed"))
    implementation(project(":repository:report-profile"))
    implementation(project(":repository:identity-feed"))
    implementation(project(":repository:event-profile"))
    implementation(project(":repository:weather-feed"))
    implementation(project(":repository:media-profile"))
    implementation(project(":repository:todo-feed"))
    implementation(project(":repository:group-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}