plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:location-contact"))
    implementation(project(":core:notification-contact"))
    implementation(project(":core:todo-login"))
    implementation(project(":core:log-contact"))
    implementation(project(":core:share"))
    implementation(project(":core:report-login"))
    implementation(project(":core:timer-contact"))
    implementation(project(":core:cart-login"))
    implementation(project(":core:session-contact"))
    implementation(project(":core:audio-login"))
    implementation(project(":core:network-login"))
    implementation(project(":core:search"))
    implementation(project(":core:contact-identity"))
    implementation(project(":core:task-login"))
    implementation(project(":core:timer"))
    implementation(project(":core:push"))
    implementation(project(":core:map-login"))
    implementation(project(":core:status"))
    implementation(project(":core:document-contact"))
    implementation(project(":core:media-login"))
    implementation(project(":core:group-login"))
    implementation(project(":core:file-login"))
    implementation(project(":core:file-contact"))
    implementation(project(":core:playlist"))
    implementation(project(":core:location-login"))
    implementation(project(":core:account-login"))
    implementation(project(":core:gallery"))
    implementation(project(":core:alarm"))
    implementation(project(":core:video-login"))
    implementation(project(":core:session-login"))
    implementation(project(":core:sync"))
    implementation(project(":core:comment"))
    implementation(project(":core:photo-login"))
    implementation(project(":core:calendar"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}