plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:location-comment"))
    implementation(project(":repository:todo-comment"))
    implementation(project(":repository:forecast-post"))
    implementation(project(":repository:report-post"))
    implementation(project(":repository:cart-location"))
    implementation(project(":repository:podcast-comment"))
    implementation(project(":repository:user-search"))
    implementation(project(":repository:push-search"))
    implementation(project(":repository:sync-search"))
    implementation(project(":repository:checkout-post"))
    implementation(project(":repository:map-search"))
    implementation(project(":repository:setting-comment"))
    implementation(project(":repository:share-comment"))
    implementation(project(":repository:push-location"))
    implementation(project(":repository:podcast-post"))
    implementation(project(":repository:comment-search"))
    implementation(project(":repository:cart-post"))
    implementation(project(":repository:cart-search"))
    implementation(project(":repository:post-comment"))
    implementation(project(":repository:user-post"))
    implementation(project(":repository:session-comment"))
    implementation(project(":repository:event-search"))
    implementation(project(":repository:playlist-search"))
    implementation(project(":repository:identity-post"))
    implementation(project(":repository:notification-comment"))
    implementation(project(":repository:document-comment"))
    implementation(project(":repository:comment-comment"))
    implementation(project(":repository:search-search"))
    implementation(project(":repository:comment-location"))
    implementation(project(":repository:search-location"))
    implementation(project(":repository:metric-comment"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}