plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:login-contact"))
    implementation(project(":core:timer-login"))
    implementation(project(":core:audio"))
    implementation(project(":core:message-contact"))
    implementation(project(":core:metric-contact"))
    implementation(project(":core:article-login"))
    implementation(project(":core:event-login"))
    implementation(project(":core:sync-login"))
    implementation(project(":core:profile"))
    implementation(project(":core:user-contact"))
    implementation(project(":core:contact-login"))
    implementation(project(":core:session"))
    implementation(project(":core:share"))
    implementation(project(":core:post-login"))
    implementation(project(":core:notification-login"))
    implementation(project(":core:media-contact"))
    implementation(project(":core:contact-contact"))
    implementation(project(":core:sync-contact"))
    implementation(project(":core:report-contact"))
    implementation(project(":core:group-login"))
    implementation(project(":core:contact"))
    implementation(project(":core:sync"))
    implementation(project(":core:group"))
    implementation(project(":core:message-login"))
    implementation(project(":core:article"))
    implementation(project(":core:metric-login"))
    implementation(project(":core:checkout-login"))
    implementation(project(":core:analytics-contact"))
    implementation(project(":core:podcast"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}