plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:session-cart"))
    implementation(project(":repository:post-cart"))
    implementation(project(":repository:message-checkout"))
    implementation(project(":repository:photo-checkout"))
    implementation(project(":repository:event-cart"))
    implementation(project(":repository:login-cart"))
    implementation(project(":repository:notification-checkout"))
    implementation(project(":repository:analytics-cart"))
    implementation(project(":repository:alarm-cart"))
    implementation(project(":repository:podcast-checkout"))
    implementation(project(":repository:feed-cart"))
    implementation(project(":repository:log-checkout"))
    implementation(project(":repository:analytics-checkout"))
    implementation(project(":repository:timer-cart"))
    implementation(project(":repository:comment-cart"))
    implementation(project(":repository:media-checkout"))
    implementation(project(":repository:group-checkout"))
    implementation(project(":repository:document-checkout"))
    implementation(project(":repository:report-cart"))
    implementation(project(":repository:group-cart"))
    implementation(project(":repository:account-cart"))
    implementation(project(":repository:log-cart"))
    implementation(project(":repository:audio-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}