plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:note-cart"))
    implementation(project(":domain:metric-checkout"))
    implementation(project(":domain:comment-user"))
    implementation(project(":domain:metric-cart"))
    implementation(project(":domain:forecast-cart"))
    implementation(project(":domain:account-cart"))
    implementation(project(":domain:report-cart"))
    implementation(project(":domain:playlist-cart"))
    implementation(project(":domain:log-user"))
    implementation(project(":domain:gallery-cart"))
    implementation(project(":domain:task-user"))
    implementation(project(":domain:alarm-checkout"))
    implementation(project(":domain:search-user"))
    implementation(project(":domain:list-cart"))
    implementation(project(":domain:identity-cart"))
    implementation(project(":domain:setting-user"))
    implementation(project(":domain:document-user"))
    implementation(project(":domain:todo-user"))
    implementation(project(":domain:profile-cart"))
    implementation(project(":domain:user-user"))
    implementation(project(":domain:audio-checkout"))
    implementation(project(":domain:session-user"))
    implementation(project(":domain:file-user"))
    implementation(project(":domain:media-cart"))
    implementation(project(":domain:feed-cart"))
    implementation(project(":domain:search-cart"))
    implementation(project(":domain:checkout-cart"))
    implementation(project(":domain:article-checkout"))
    implementation(project(":domain:list-checkout"))
    implementation(project(":domain:event-user"))
    implementation(project(":domain:document-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}