plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:log-user"))
    implementation(project(":domain:sync-profile"))
    implementation(project(":domain:share-profile"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:contact-profile"))
    implementation(project(":domain:identity-feed"))
    implementation(project(":domain:post-profile"))
    implementation(project(":domain:status-profile"))
    implementation(project(":domain:cart-comment"))
    implementation(project(":domain:video-user"))
    implementation(project(":domain:message-user"))
    implementation(project(":domain:podcast-feed"))
    implementation(project(":domain:document-user"))
    implementation(project(":domain:message-feed"))
    implementation(project(":domain:media-profile"))
    implementation(project(":domain:document-feed"))
    implementation(project(":domain:news-user"))
    implementation(project(":domain:todo-user"))
    implementation(project(":domain:log-profile"))
    implementation(project(":domain:photo-feed"))
    implementation(project(":domain:group-feed"))
    implementation(project(":domain:identity-comment"))
    implementation(project(":domain:report-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}