plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:podcast-contact"))
    implementation(project(":core:photo"))
    implementation(project(":core:search"))
    implementation(project(":core:log"))
    implementation(project(":core:contact-login"))
    implementation(project(":core:document"))
    implementation(project(":core:message-contact"))
    implementation(project(":core:article"))
    implementation(project(":core:contact"))
    implementation(project(":core:playlist"))
    implementation(project(":core:location-contact"))
    implementation(project(":core:identity-contact"))
    implementation(project(":core:status-contact"))
    implementation(project(":core:notification-contact"))
    implementation(project(":core:analytics-contact"))
    implementation(project(":core:timer"))
    implementation(project(":core:user-contact"))
    implementation(project(":core:checkout"))
    implementation(project(":core:file-contact"))
    implementation(project(":core:file"))
    implementation(project(":core:status"))
    implementation(project(":core:feed-login"))
    implementation(project(":core:log-contact"))
    implementation(project(":core:report"))
    implementation(project(":core:location"))
    implementation(project(":core:checkout-contact"))
    implementation(project(":core:alarm"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}