plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:metric-identity"))
    implementation(project(":feature:comment-identity"))
    implementation(project(":feature:contact-checkout"))
    implementation(project(":feature:report-checkout"))
    implementation(project(":feature:task-identity"))
    implementation(project(":feature:audio-identity"))
    implementation(project(":feature:sync-checkout"))
    implementation(project(":feature:video-identity"))
    implementation(project(":feature:message-checkout"))
    implementation(project(":feature:article-identity"))
    implementation(project(":feature:news-login"))
    implementation(project(":feature:session-identity"))
    implementation(project(":feature:cart-checkout"))
    implementation(project(":feature:notification-login"))
    implementation(project(":feature:analytics-identity"))
    implementation(project(":feature:playlist-login"))
    implementation(project(":feature:file-identity"))
    implementation(project(":feature:map-identity"))
    implementation(project(":feature:weather-identity"))
    implementation(project(":feature:network-identity"))
    implementation(project(":feature:checkout-checkout"))
    implementation(project(":feature:sync-identity"))
    implementation(project(":feature:forecast-login"))
    implementation(project(":feature:post-checkout"))
    implementation(project(":feature:note-login"))
    implementation(project(":feature:user-checkout"))
    implementation(project(":feature:gallery-login"))
    implementation(project(":feature:media-login"))
    implementation(project(":feature:task-login"))
    implementation(project(":feature:network-checkout"))
    implementation(project(":feature:forecast-identity"))
    implementation(project(":feature:group-login"))
    implementation(project(":feature:status-login"))
    implementation(project(":feature:metric-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}