plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:article-user"))
    implementation(project(":domain:document-user"))
    implementation(project(":domain:identity-comment"))
    implementation(project(":domain:todo-feed"))
    implementation(project(":domain:note-profile"))
    implementation(project(":domain:task-feed"))
    implementation(project(":domain:map-profile"))
    implementation(project(":domain:log-feed"))
    implementation(project(":domain:status-user"))
    implementation(project(":domain:note-user"))
    implementation(project(":domain:push-feed"))
    implementation(project(":domain:media-profile"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:analytics-user"))
    implementation(project(":domain:metric-feed"))
    implementation(project(":domain:media-feed"))
    implementation(project(":domain:alarm-user"))
    implementation(project(":domain:location-profile"))
    implementation(project(":domain:list-feed"))
    implementation(project(":domain:metric-profile"))
    implementation(project(":domain:gallery-user"))
    implementation(project(":domain:analytics-feed"))
    implementation(project(":domain:feed-profile"))
    implementation(project(":domain:location-feed"))
    implementation(project(":domain:playlist-profile"))
    implementation(project(":domain:task-profile"))
    implementation(project(":domain:analytics-profile"))
    implementation(project(":domain:comment-feed"))
    implementation(project(":domain:feed-feed"))
    implementation(project(":domain:share-user"))
    implementation(project(":domain:file-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}