plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:notification-identity"))
    implementation(project(":feature:login-checkout"))
    implementation(project(":feature:notification-checkout"))
    implementation(project(":feature:alarm-checkout"))
    implementation(project(":feature:playlist-checkout"))
    implementation(project(":feature:contact-checkout"))
    implementation(project(":feature:todo-identity"))
    implementation(project(":feature:network-identity"))
    implementation(project(":feature:video-identity"))
    implementation(project(":feature:push-checkout"))
    implementation(project(":feature:profile-identity"))
    implementation(project(":feature:video-checkout"))
    implementation(project(":feature:group-cart"))
    implementation(project(":feature:message-identity"))
    implementation(project(":feature:log-cart"))
    implementation(project(":feature:list-identity"))
    implementation(project(":feature:news-cart"))
    implementation(project(":feature:forecast-identity"))
    implementation(project(":feature:share-checkout"))
    implementation(project(":feature:login-cart"))
    implementation(project(":feature:profile-cart"))
    implementation(project(":feature:metric-identity"))
    implementation(project(":feature:notification-cart"))
    implementation(project(":feature:setting-checkout"))
    implementation(project(":feature:document-identity"))
    implementation(project(":feature:push-user"))
    implementation(project(":feature:comment-cart"))
    implementation(project(":feature:task-checkout"))
    implementation(project(":feature:cart-identity"))
    implementation(project(":feature:profile-checkout"))
    implementation(project(":feature:group-identity"))
    implementation(project(":feature:analytics-identity"))
    implementation(project(":feature:session-cart"))
    implementation(project(":feature:sync-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}