plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:alarm-feed"))
    implementation(project(":domain:user-user"))
    implementation(project(":domain:location-user"))
    implementation(project(":domain:todo-profile"))
    implementation(project(":domain:media-profile"))
    implementation(project(":domain:push-feed"))
    implementation(project(":domain:podcast-profile"))
    implementation(project(":domain:session-profile"))
    implementation(project(":domain:forecast-feed"))
    implementation(project(":domain:sync-profile"))
    implementation(project(":domain:post-user"))
    implementation(project(":domain:location-profile"))
    implementation(project(":domain:video-user"))
    implementation(project(":domain:analytics-user"))
    implementation(project(":domain:metric-user"))
    implementation(project(":domain:login-comment"))
    implementation(project(":domain:status-user"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:file-feed"))
    implementation(project(":domain:network-user"))
    implementation(project(":domain:share-feed"))
    implementation(project(":domain:news-user"))
    implementation(project(":domain:task-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}