plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:article-feed"))
    implementation(project(":domain:notification-user"))
    implementation(project(":domain:share-feed"))
    implementation(project(":domain:account-feed"))
    implementation(project(":domain:profile-feed"))
    implementation(project(":domain:user-comment"))
    implementation(project(":domain:analytics-feed"))
    implementation(project(":domain:weather-user"))
    implementation(project(":domain:comment-user"))
    implementation(project(":domain:task-profile"))
    implementation(project(":domain:network-user"))
    implementation(project(":domain:article-profile"))
    implementation(project(":domain:identity-feed"))
    implementation(project(":domain:podcast-profile"))
    implementation(project(":domain:document-feed"))
    implementation(project(":domain:sync-user"))
    implementation(project(":domain:note-user"))
    implementation(project(":domain:push-feed"))
    implementation(project(":domain:report-profile"))
    implementation(project(":domain:login-comment"))
    implementation(project(":domain:forecast-feed"))
    implementation(project(":domain:event-feed"))
    implementation(project(":domain:list-feed"))
    implementation(project(":domain:media-profile"))
    implementation(project(":domain:push-comment"))
    implementation(project(":domain:photo-feed"))
    implementation(project(":domain:event-user"))
    implementation(project(":domain:list-user"))
    implementation(project(":domain:status-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}