plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:video-user"))
    implementation(project(":repository:podcast-feed"))
    implementation(project(":repository:podcast-profile"))
    implementation(project(":repository:todo-feed"))
    implementation(project(":repository:notification-feed"))
    implementation(project(":repository:location-feed"))
    implementation(project(":repository:timer-profile"))
    implementation(project(":repository:list-user"))
    implementation(project(":repository:weather-profile"))
    implementation(project(":repository:profile-profile"))
    implementation(project(":repository:log-feed"))
    implementation(project(":repository:setting-profile"))
    implementation(project(":repository:feed-profile"))
    implementation(project(":repository:search-profile"))
    implementation(project(":repository:playlist-user"))
    implementation(project(":repository:push-profile"))
    implementation(project(":repository:weather-user"))
    implementation(project(":repository:contact-profile"))
    implementation(project(":repository:network-feed"))
    implementation(project(":repository:media-feed"))
    implementation(project(":repository:gallery-feed"))
    implementation(project(":repository:analytics-feed"))
    implementation(project(":repository:playlist-profile"))
    implementation(project(":repository:article-profile"))
    implementation(project(":repository:news-profile"))
    implementation(project(":repository:media-profile"))
    implementation(project(":repository:audio-user"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}