plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:note-checkout"))
    implementation(project(":domain:contact-user"))
    implementation(project(":domain:analytics-cart"))
    implementation(project(":domain:todo-checkout"))
    implementation(project(":domain:forecast-checkout"))
    implementation(project(":domain:todo-user"))
    implementation(project(":domain:account-user"))
    implementation(project(":domain:playlist-cart"))
    implementation(project(":domain:document-checkout"))
    implementation(project(":domain:playlist-checkout"))
    implementation(project(":domain:profile-user"))
    implementation(project(":domain:forecast-cart"))
    implementation(project(":domain:setting-user"))
    implementation(project(":domain:note-cart"))
    implementation(project(":domain:notification-cart"))
    implementation(project(":domain:post-cart"))
    implementation(project(":domain:task-user"))
    implementation(project(":domain:report-cart"))
    implementation(project(":domain:event-cart"))
    implementation(project(":domain:gallery-cart"))
    implementation(project(":domain:sync-user"))
    implementation(project(":domain:article-checkout"))
    implementation(project(":domain:location-user"))
    implementation(project(":domain:todo-cart"))
    implementation(project(":domain:metric-user"))
    implementation(project(":domain:weather-cart"))
    implementation(project(":domain:checkout-user"))
    implementation(project(":domain:network-cart"))
    implementation(project(":domain:session-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}