plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:photo-cart"))
    implementation(project(":feature:news-checkout"))
    implementation(project(":feature:photo-identity"))
    implementation(project(":feature:setting-checkout"))
    implementation(project(":feature:contact-checkout"))
    implementation(project(":feature:gallery-checkout"))
    implementation(project(":feature:identity-identity"))
    implementation(project(":feature:map-identity"))
    implementation(project(":feature:photo-checkout"))
    implementation(project(":feature:list-checkout"))
    implementation(project(":feature:report-identity"))
    implementation(project(":feature:cart-user"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:push-checkout"))
    implementation(project(":feature:video-cart"))
    implementation(project(":feature:map-cart"))
    implementation(project(":feature:news-identity"))
    implementation(project(":feature:media-identity"))
    implementation(project(":feature:cart-cart"))
    implementation(project(":feature:comment-cart"))
    implementation(project(":feature:weather-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}