plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:contact"))
    implementation(project(":core:group-contact"))
    implementation(project(":core:news-login"))
    implementation(project(":core:push"))
    implementation(project(":core:audio-login"))
    implementation(project(":core:network-login"))
    implementation(project(":core:search-contact"))
    implementation(project(":core:document"))
    implementation(project(":core:event"))
    implementation(project(":core:todo"))
    implementation(project(":core:status"))
    implementation(project(":core:metric-contact"))
    implementation(project(":core:location-contact"))
    implementation(project(":core:session-login"))
    implementation(project(":core:push-identity"))
    implementation(project(":core:session"))
    implementation(project(":core:search-login"))
    implementation(project(":core:log"))
    implementation(project(":core:message"))
    implementation(project(":core:note"))
    implementation(project(":core:playlist"))
    implementation(project(":core:group-login"))
    implementation(project(":core:calendar"))
    implementation(project(":core:post-contact"))
    implementation(project(":core:group"))
    implementation(project(":core:message-contact"))
    implementation(project(":core:video-contact"))
    implementation(project(":core:article"))
    implementation(project(":core:playlist-login"))
    implementation(project(":core:identity-contact"))
    implementation(project(":core:location-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}