plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:identity-checkout"))
    implementation(project(":feature:account-login"))
    implementation(project(":feature:account-identity"))
    implementation(project(":feature:alarm-login"))
    implementation(project(":feature:report-checkout"))
    implementation(project(":feature:log-identity"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:search-identity"))
    implementation(project(":feature:feed-identity"))
    implementation(project(":feature:notification-identity"))
    implementation(project(":feature:location-checkout"))
    implementation(project(":feature:cart-identity"))
    implementation(project(":feature:checkout-checkout"))
    implementation(project(":feature:audio-identity"))
    implementation(project(":feature:analytics-checkout"))
    implementation(project(":feature:news-identity"))
    implementation(project(":feature:media-identity"))
    implementation(project(":feature:task-login"))
    implementation(project(":feature:article-identity"))
    implementation(project(":feature:contact-identity"))
    implementation(project(":feature:search-checkout"))
    implementation(project(":feature:session-identity"))
    implementation(project(":feature:sync-checkout"))
    implementation(project(":feature:message-login"))
    implementation(project(":feature:media-login"))
    implementation(project(":feature:status-identity"))
    implementation(project(":feature:alarm-identity"))
    implementation(project(":feature:metric-login"))
    implementation(project(":feature:timer-identity"))
    implementation(project(":feature:location-login"))
    implementation(project(":feature:video-login"))
    implementation(project(":feature:list-identity"))
    implementation(project(":feature:report-identity"))
    implementation(project(":feature:document-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}