plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:feed-search"))
    implementation(project(":repository:profile-location"))
    implementation(project(":repository:location-post"))
    implementation(project(":repository:sync-post"))
    implementation(project(":repository:video-comment"))
    implementation(project(":repository:media-comment"))
    implementation(project(":repository:document-search"))
    implementation(project(":repository:checkout-search"))
    implementation(project(":repository:analytics-search"))
    implementation(project(":repository:contact-post"))
    implementation(project(":repository:cart-post"))
    implementation(project(":repository:feed-location"))
    implementation(project(":repository:file-post"))
    implementation(project(":repository:notification-comment"))
    implementation(project(":repository:log-comment"))
    implementation(project(":repository:identity-location"))
    implementation(project(":repository:contact-location"))
    implementation(project(":repository:media-search"))
    implementation(project(":repository:network-comment"))
    implementation(project(":repository:share-comment"))
    implementation(project(":repository:todo-search"))
    implementation(project(":repository:alarm-comment"))
    implementation(project(":repository:audio-comment"))
    implementation(project(":repository:share-post"))
    implementation(project(":repository:cart-location"))
    implementation(project(":repository:notification-post"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}