plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:list-identity"))
    implementation(project(":feature:notification-checkout"))
    implementation(project(":feature:media-checkout"))
    implementation(project(":feature:status-cart"))
    implementation(project(":feature:report-checkout"))
    implementation(project(":feature:identity-identity"))
    implementation(project(":feature:task-identity"))
    implementation(project(":feature:weather-checkout"))
    implementation(project(":feature:notification-identity"))
    implementation(project(":feature:network-identity"))
    implementation(project(":feature:user-identity"))
    implementation(project(":feature:audio-identity"))
    implementation(project(":feature:cart-user"))
    implementation(project(":feature:document-identity"))
    implementation(project(":feature:video-checkout"))
    implementation(project(":feature:note-cart"))
    implementation(project(":feature:audio-checkout"))
    implementation(project(":feature:search-identity"))
    implementation(project(":feature:group-identity"))
    implementation(project(":feature:report-identity"))
    implementation(project(":feature:post-cart"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:share-cart"))
    implementation(project(":feature:setting-checkout"))
    implementation(project(":feature:calendar-identity"))
    implementation(project(":feature:setting-cart"))
    implementation(project(":feature:metric-checkout"))
    implementation(project(":feature:note-identity"))
    implementation(project(":feature:file-identity"))
    implementation(project(":feature:video-cart"))
    implementation(project(":feature:playlist-checkout"))
    implementation(project(":feature:list-cart"))
    implementation(project(":feature:session-identity"))
    implementation(project(":feature:analytics-cart"))
    implementation(project(":feature:login-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}