plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:podcast-user"))
    implementation(project(":repository:audio-feed"))
    implementation(project(":repository:message-profile"))
    implementation(project(":repository:account-profile"))
    implementation(project(":repository:weather-feed"))
    implementation(project(":repository:playlist-user"))
    implementation(project(":repository:report-profile"))
    implementation(project(":repository:identity-profile"))
    implementation(project(":repository:notification-profile"))
    implementation(project(":repository:post-feed"))
    implementation(project(":repository:note-profile"))
    implementation(project(":repository:map-user"))
    implementation(project(":repository:file-profile"))
    implementation(project(":repository:location-feed"))
    implementation(project(":repository:push-feed"))
    implementation(project(":repository:photo-profile"))
    implementation(project(":repository:playlist-profile"))
    implementation(project(":repository:comment-feed"))
    implementation(project(":repository:session-profile"))
    implementation(project(":repository:list-profile"))
    implementation(project(":repository:setting-feed"))
    implementation(project(":repository:session-feed"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}