plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:post-identity"))
    implementation(project(":feature:identity-checkout"))
    implementation(project(":feature:todo-login"))
    implementation(project(":feature:setting-checkout"))
    implementation(project(":feature:alarm-login"))
    implementation(project(":feature:profile-identity"))
    implementation(project(":feature:setting-login"))
    implementation(project(":feature:map-login"))
    implementation(project(":feature:gallery-login"))
    implementation(project(":feature:comment-checkout"))
    implementation(project(":feature:photo-identity"))
    implementation(project(":feature:calendar-login"))
    implementation(project(":feature:location-identity"))
    implementation(project(":feature:share-identity"))
    implementation(project(":feature:weather-login"))
    implementation(project(":feature:session-checkout"))
    implementation(project(":feature:network-identity"))
    implementation(project(":feature:feed-identity"))
    implementation(project(":feature:feed-checkout"))
    implementation(project(":feature:report-identity"))
    implementation(project(":feature:message-checkout"))
    implementation(project(":feature:playlist-login"))
    implementation(project(":feature:group-identity"))
    implementation(project(":feature:status-identity"))
    implementation(project(":feature:network-login"))
    implementation(project(":feature:news-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}