plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":feature:post-identity"))
    implementation(project(":feature:push-cart"))
    implementation(project(":feature:task-cart"))
    implementation(project(":feature:identity-identity"))
    implementation(project(":feature:profile-checkout"))
    implementation(project(":feature:media-identity"))
    implementation(project(":feature:document-cart"))
    implementation(project(":feature:map-cart"))
    implementation(project(":feature:location-checkout"))
    implementation(project(":feature:contact-cart"))
    implementation(project(":feature:document-checkout"))
    implementation(project(":feature:message-checkout"))
    implementation(project(":feature:event-identity"))
    implementation(project(":feature:comment-cart"))
    implementation(project(":feature:calendar-identity"))
    implementation(project(":feature:list-identity"))
    implementation(project(":feature:user-cart"))
    implementation(project(":feature:calendar-cart"))
    implementation(project(":feature:network-cart"))
    implementation(project(":feature:login-user"))
    implementation(project(":feature:contact-checkout"))
    implementation(project(":feature:event-checkout"))
    implementation(project(":feature:metric-identity"))
    implementation(project(":feature:weather-identity"))
    implementation(project(":feature:todo-cart"))
    implementation(project(":feature:group-checkout"))
    implementation(project(":feature:news-cart"))
    implementation(project(":feature:analytics-identity"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}