plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:event"))
    implementation(project(":core:post-login"))
    implementation(project(":core:account-login"))
    implementation(project(":core:status-login"))
    implementation(project(":core:checkout-contact"))
    implementation(project(":core:push-contact"))
    implementation(project(":core:push-login"))
    implementation(project(":core:event-login"))
    implementation(project(":core:todo-contact"))
    implementation(project(":core:analytics-login"))
    implementation(project(":core:setting-contact"))
    implementation(project(":core:contact-identity"))
    implementation(project(":core:cart-login"))
    implementation(project(":core:alarm"))
    implementation(project(":core:push-identity"))
    implementation(project(":core:timer"))
    implementation(project(":core:gallery-login"))
    implementation(project(":core:file-contact"))
    implementation(project(":core:notification-login"))
    implementation(project(":core:calendar-contact"))
    implementation(project(":core:user-contact"))
    implementation(project(":core:location"))
    implementation(project(":core:notification-contact"))
    implementation(project(":core:playlist"))
    implementation(project(":core:profile-login"))
    implementation(project(":core:share-contact"))
    implementation(project(":core:alarm-login"))
    implementation(project(":core:checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}